spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: AIGOU_PLAT
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true #使用ip注册到注册中心
server:
  port: 8899

---
spring:
  profiles: test #测试环境
  application: 
    name: AIGOU_PLAT #服务名字
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka #注册中心地址 
  instance:
    prefer-ip-address: true #使用ip注册到注册中心
server:
  port: 9988 #环境切换 端口