spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev  
  application:
    name: AIGOU_PLAT
eureka:
  client:
    service-Url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true  
server:
  port: 8899

---
spring:
  profiles: test 
  application: 
    name: AIGOU_PLAT 
eureka:
  client:
    service-Url:
      defaultZone: http://127.0.0.1:7001/eureka 
  instance:
    prefer-ip-address: true 
server:
  port: 9988 